### ISSUE TITLE
Are you reporting dN/dS or pN/pS?

### ISSUE THREAD

**Issue by flashton2003** [adelq/dnds#2]
I have been using this helpful blog post to learn about dN/dS ratios.

http://bioinformatics.cvr.ac.uk/blog/calculating-dnds-for-ngs-datasets/

However, following through their example with your code there was a discrepancy.

According to the scheme set out in that blog post, you are reporting the pN/pS. Following onto the [Nei & Gojobori, 1986 paper](https://academic.oup.com/mbe/article/3/5/418/988012/Simple-methods-for-estimating-the-numbers-of), which the blog post authors reference, I think the part you omitted was the conversion to per site results according to Jukes & Cantor 1967.

When I add in the below, I get the same result as the blog post authors for their sequence (0.1247)

`pn = non_subs / non_sites`
`ps = syn_subs / syn_sites`
`dn = -(3 / 4) * log(1 - (4 * pn / 3))`
`ds = -(3 / 4) * log(1 - (4 * ps / 3))`

What are your thoughts on that discrepancy?

**Comment by adelq** [comment]
This program performs an exact count method calculation of dN/dS, or the ratio of non-synonymous substitutions per non-synonymous site to synonymous substitutions per synonymous site.

Thanks for the linked blogpost, it was quite informative. However, the method performed by Jukes & Cantor 1967 calculates an estimate of dN/dS by attempting to correct for multiple substitution pathways, as mentioned in Nei & Gobobori 1986 and [Pond et. al 2009](http://www.hyphy.org/pubs/hyphybook2007.pdf).

This is an explicit non-goal of this project, as there are numerous models to account for other factors in sequence substitutions, such as codon bias, alternative substitutions pathways, transition vs transverse mutation ratio, etc. There are many software packages that perform efficient estimates of the dN/dS ratio using models and heuristic methods to reduce calculations and lookups, but I was unable to find a package that performs an exact count, so I wrote my own. You may also check out the sources linked in the code comments for a clear explanation of the exact count method, though unfortunately some have vanished due to linkrot.

You are more than welcome to adapt this package to your own needs, I have added an [MIT license](https://github.com/adelq/dnds/blob/master/LICENSE) to provide an explicit grant to use the software as you wish. I find the current simple model easy to understand and easy to modify and build upon, and satisfied the need for an exact count I had at the time. Thanks!

**Comment by flashton2003** [comment]
Ok, thanks for the explanation.

**Comment by adelq** [comment]
It seems that this interpretation of dN/dS is perhaps not standard/universal, so I'm reopening this issue to add more documentation and include a "proper" dN/dS calculation as well.

**Comment by adelq** [comment]
Fixed in #4, thanks!
