### ISSUE TITLE
incorrect dN/dS computations?

### ISSUE THREAD

**Issue by idavydov** [adelq/dnds#3]
Sorry for reporting this. I've noticed your code. And it seems that this is not a conventional way of computing dN/dS based on counting. Probably you are not using this code at the moment, but I just want to warn you and people who might use this code.

The classical and improved method of computing dN/dS based on counts are described in the 1986 [paper by Nei Gojobori](https://doi.org/10.1093/oxfordjournals.molbev.a040410) or [here](http://bioinformatics.cvr.ac.uk/blog/calculating-dnds-for-ngs-datasets/). What you are computing looks more like p_N/p_S, which is fine, as long as people are aware that it is another estimate, with different properties. Also, I am not sure that you are correcting for:

1. different trajectories for multinucleotide substitutions (i.e. TTT -> TCT -> TCC and TTT -> TTC -> TCC)
2. stop codons; substitutions involving stop codon should not be considered (for computing N and for mutation trajectories).

There is a reference implementation in C available in [PAML](http://abacus.gene.ucl.ac.uk/software/paml.html) (function `DistanceMatNG86`), it might be a good idea to compare your implementation with it.

Again, sorry for intruding. It's just a friendly message, so you are aware.

**Comment by adelq** [comment]
Thanks for the informative note. This was discussed previously (issue #2) and it seems like it's standard to report this value as pN/pS, not dN/dS as misleadingly stated earlier.

I wrote this code for the specific purpose of calculating a precise "dN/dS" value according a specification that did not include additional corrections, including but not limited to codon biases, multiple and alternative substitutions, etc. It fulfilled its purpose quite well, but is not currently in use.

Since it appears this use of terminology is misleading and contentious, I'll be updating the documentation to make explicit what calculations and assumptions are made, and perhaps implement a full "classical" dN/dS. I would also accept a pull request with those changes if you (or @flashton2003) beat me to it.

Thanks for dropping by, I appreciate your feedback!

**Comment by idavydov** [comment]
Great, thanks for the clarifications!

I have a rather simplistic implementation myself, but it is not at a stage when I can make a pull request. If it will ever become more mature, I will share the code with you one way or another.

**Comment by adelq** [comment]
Awesome, thanks!

**Comment by adelq** [comment]
Fixed in #4, thanks!
